# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(817, 1107)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.media_slidebar = QtWidgets.QHBoxLayout()
        self.media_slidebar.setSpacing(6)
        self.media_slidebar.setObjectName("media_slidebar")
        self.currentTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.currentTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.currentTimeLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.currentTimeLabel.setObjectName("currentTimeLabel")
        self.media_slidebar.addWidget(self.currentTimeLabel)
        self.timeSlider = QtWidgets.QSlider(self.centralWidget)
        self.timeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.timeSlider.setObjectName("timeSlider")
        self.media_slidebar.addWidget(self.timeSlider)
        self.totalTimeLabel = QtWidgets.QLabel(self.centralWidget)
        self.totalTimeLabel.setMinimumSize(QtCore.QSize(80, 0))
        self.totalTimeLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalTimeLabel.setObjectName("totalTimeLabel")
        self.media_slidebar.addWidget(self.totalTimeLabel)
        self.gridLayout.addLayout(self.media_slidebar, 1, 0, 1, 1)
        self.label_header = QtWidgets.QLabel(self.centralWidget)
        self.label_header.setObjectName("label_header")
        self.gridLayout.addWidget(self.label_header, 12, 0, 1, 1)
        self.playlistView = QtWidgets.QListView(self.centralWidget)
        self.playlistView.setAcceptDrops(True)
        self.playlistView.setProperty("showDropIndicator", True)
        self.playlistView.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.playlistView.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.playlistView.setAlternatingRowColors(True)
        self.playlistView.setUniformItemSizes(True)
        self.playlistView.setObjectName("playlistView")
        self.gridLayout.addWidget(self.playlistView, 0, 0, 1, 1)
        self.button_loadsub = QtWidgets.QPushButton(self.centralWidget)
        self.button_loadsub.setObjectName("button_loadsub")
        self.gridLayout.addWidget(self.button_loadsub, 11, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.resolution_value = QtWidgets.QLabel(self.centralWidget)
        self.resolution_value.setText("")
        self.resolution_value.setObjectName("resolution_value")
        self.gridLayout_2.addWidget(self.resolution_value, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.audio_list = QtWidgets.QListView(self.centralWidget)
        self.audio_list.setObjectName("audio_list")
        self.gridLayout_2.addWidget(self.audio_list, 2, 0, 1, 1)
        self.sub_list = QtWidgets.QListView(self.centralWidget)
        self.sub_list.setObjectName("sub_list")
        self.gridLayout_2.addWidget(self.sub_list, 4, 0, 1, 1)
        self.label_resolution = QtWidgets.QLabel(self.centralWidget)
        self.label_resolution.setObjectName("label_resolution")
        self.gridLayout_2.addWidget(self.label_resolution, 0, 0, 1, 1)
        self.label_sublist = QtWidgets.QLabel(self.centralWidget)
        self.label_sublist.setObjectName("label_sublist")
        self.gridLayout_2.addWidget(self.label_sublist, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 6, 0, 1, 1)
        self.media_info = QtWidgets.QHBoxLayout()
        self.media_info.setSpacing(6)
        self.media_info.setObjectName("media_info")
        self.previousButton = QtWidgets.QPushButton(self.centralWidget)
        self.previousButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/control-skip-180.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.previousButton.setIcon(icon)
        self.previousButton.setObjectName("previousButton")
        self.media_info.addWidget(self.previousButton)
        self.playButton = QtWidgets.QPushButton(self.centralWidget)
        self.playButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/control.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.playButton.setIcon(icon1)
        self.playButton.setObjectName("playButton")
        self.media_info.addWidget(self.playButton)
        self.pauseButton = QtWidgets.QPushButton(self.centralWidget)
        self.pauseButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/control-pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pauseButton.setIcon(icon2)
        self.pauseButton.setObjectName("pauseButton")
        self.media_info.addWidget(self.pauseButton)
        self.stopButton = QtWidgets.QPushButton(self.centralWidget)
        self.stopButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/control-stop-square.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon3)
        self.stopButton.setObjectName("stopButton")
        self.media_info.addWidget(self.stopButton)
        self.back1s = QtWidgets.QToolButton(self.centralWidget)
        self.back1s.setObjectName("back1s")
        self.media_info.addWidget(self.back1s)
        self.next1s = QtWidgets.QToolButton(self.centralWidget)
        self.next1s.setObjectName("next1s")
        self.media_info.addWidget(self.next1s)
        self.nextButton = QtWidgets.QPushButton(self.centralWidget)
        self.nextButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/control-skip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.nextButton.setIcon(icon4)
        self.nextButton.setObjectName("nextButton")
        self.media_info.addWidget(self.nextButton)
        self.viewButton = QtWidgets.QPushButton(self.centralWidget)
        self.viewButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/application-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewButton.setIcon(icon5)
        self.viewButton.setCheckable(True)
        self.viewButton.setObjectName("viewButton")
        self.media_info.addWidget(self.viewButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.media_info.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/speaker-volume.png"))
        self.label.setObjectName("label")
        self.media_info.addWidget(self.label)
        self.volumeSlider = QtWidgets.QSlider(self.centralWidget)
        self.volumeSlider.setMaximum(100)
        self.volumeSlider.setProperty("value", 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName("volumeSlider")
        self.media_info.addWidget(self.volumeSlider)
        self.gridLayout.addLayout(self.media_info, 2, 0, 1, 1)
        self.text_header = QtWidgets.QLineEdit(self.centralWidget)
        self.text_header.setObjectName("text_header")
        self.gridLayout.addWidget(self.text_header, 13, 0, 1, 1)
        self.label_footer = QtWidgets.QLabel(self.centralWidget)
        self.label_footer.setObjectName("label_footer")
        self.gridLayout.addWidget(self.label_footer, 14, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.finalizeButton = QtWidgets.QPushButton(self.centralWidget)
        self.finalizeButton.setObjectName("finalizeButton")
        self.horizontalLayout.addWidget(self.finalizeButton)
        self.resetButton = QtWidgets.QPushButton(self.centralWidget)
        self.resetButton.setObjectName("resetButton")
        self.horizontalLayout.addWidget(self.resetButton)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 0, 1, 1)
        self.text_footer = QtWidgets.QLineEdit(self.centralWidget)
        self.text_footer.setObjectName("text_footer")
        self.gridLayout.addWidget(self.text_footer, 15, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 817, 30))
        self.menuBar.setObjectName("menuBar")
        self.menuFIle = QtWidgets.QMenu(self.menuBar)
        self.menuFIle.setObjectName("menuFIle")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.open_file_action = QtWidgets.QAction(MainWindow)
        self.open_file_action.setObjectName("open_file_action")
        self.actionmask_in = QtWidgets.QAction(MainWindow)
        self.actionmask_in.setObjectName("actionmask_in")
        self.actionMask_Out = QtWidgets.QAction(MainWindow)
        self.actionMask_Out.setObjectName("actionMask_Out")
        self.actionAdd_Masks = QtWidgets.QAction(MainWindow)
        self.actionAdd_Masks.setObjectName("actionAdd_Masks")
        self.action_back5s = QtWidgets.QAction(MainWindow)
        self.action_back5s.setObjectName("action_back5s")
        self.action_next5s = QtWidgets.QAction(MainWindow)
        self.action_next5s.setObjectName("action_next5s")
        self.actionRemove_selected = QtWidgets.QAction(MainWindow)
        self.actionRemove_selected.setObjectName("actionRemove_selected")
        self.menuFIle.addAction(self.open_file_action)
        self.menuFIle.addAction(self.actionmask_in)
        self.menuFIle.addAction(self.actionMask_Out)
        self.menuFIle.addAction(self.actionAdd_Masks)
        self.menuFIle.addAction(self.action_back5s)
        self.menuFIle.addAction(self.action_next5s)
        self.menuFIle.addAction(self.actionRemove_selected)
        self.menuBar.addAction(self.menuFIle.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Failamp"))
        self.currentTimeLabel.setText(_translate("MainWindow", "0:00"))
        self.totalTimeLabel.setText(_translate("MainWindow", "0:00"))
        self.label_header.setText(_translate("MainWindow", "Header"))
        self.button_loadsub.setText(_translate("MainWindow", "Manual Load subtitle"))
        self.label_2.setText(_translate("MainWindow", "sub list"))
        self.label_resolution.setText(_translate("MainWindow", "Resolution"))
        self.label_sublist.setText(_translate("MainWindow", "audio list"))
        self.back1s.setText(_translate("MainWindow", "<<"))
        self.next1s.setText(_translate("MainWindow", ">>"))
        self.label_footer.setText(_translate("MainWindow", "Footer"))
        self.finalizeButton.setText(_translate("MainWindow", "Finalize"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.menuFIle.setTitle(_translate("MainWindow", "FI&le"))
        self.open_file_action.setText(_translate("MainWindow", "&Open file..."))
        self.actionmask_in.setText(_translate("MainWindow", "&Mask In"))
        self.actionMask_Out.setText(_translate("MainWindow", "Ma&sk Out"))
        self.actionAdd_Masks.setText(_translate("MainWindow", "&Add Masks"))
        self.action_back5s.setText(_translate("MainWindow", "&back 5s"))
        self.action_next5s.setText(_translate("MainWindow", "&Next 5s"))
        self.actionRemove_selected.setText(_translate("MainWindow", "Remove selected"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
